--- 
trigger:
 - main

pool:
      name: 'default'
      vmImage: 'ubuntu-latest'


steps:
- task: Bash@3
  inputs:
    targetType: 'inline'

- script: |
   sudo apt-get update

- script: |
   sudo apt-get install openjdk-17-jdk

- script: |
   sudo apt-get install maven-y




